# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gibbs_semo_uhp_only_cpp <- function(niter, K, beta_1_tk, beta_2_tk, theta_1_tk, theta_2_tk, gamma_tk, sigma2_gamma_tk, Gamma_hat_1, Gamma_hat_2, s2_hat_Gamma_1, s2_hat_Gamma_2, gamma_hat, s2_hat_gamma, a_gamma, b_gamma, Sigma_theta_init, nu_theta, Phi_theta) {
    .Call(`_FusioMRdev_gibbs_semo_uhp_only_cpp`, niter, K, beta_1_tk, beta_2_tk, theta_1_tk, theta_2_tk, gamma_tk, sigma2_gamma_tk, Gamma_hat_1, Gamma_hat_2, s2_hat_Gamma_1, s2_hat_Gamma_2, gamma_hat, s2_hat_gamma, a_gamma, b_gamma, Sigma_theta_init, nu_theta, Phi_theta)
}

gibbs_seso_uhp_only_cpp <- function(niter, K, beta_tk, theta_tk, gamma_tk, sigma2_gamma_tk, sigma2_theta_tk, Gamma_hat, gamma_hat, s2_hat_Gamma, s2_hat_gamma, a_gamma, b_gamma, a_theta, b_theta) {
    .Call(`_FusioMRdev_gibbs_seso_uhp_only_cpp`, niter, K, beta_tk, theta_tk, gamma_tk, sigma2_gamma_tk, sigma2_theta_tk, Gamma_hat, gamma_hat, s2_hat_Gamma, s2_hat_gamma, a_gamma, b_gamma, a_theta, b_theta)
}

gibbs_seso_with_chp_cpp <- function(niter, K, beta_tk, alpha_tk, eta_tk, theta_tk, gamma_tk, q_tk, Gamma_hat, gamma_hat, s2_hat_Gamma, s2_hat_gamma, sigma2_gamma_tk, sigma2_theta_tk, a_gamma, b_gamma, a_theta, b_theta, a_q, b_q) {
    .Call(`_FusioMRdev_gibbs_seso_with_chp_cpp`, niter, K, beta_tk, alpha_tk, eta_tk, theta_tk, gamma_tk, q_tk, Gamma_hat, gamma_hat, s2_hat_Gamma, s2_hat_gamma, sigma2_gamma_tk, sigma2_theta_tk, a_gamma, b_gamma, a_theta, b_theta, a_q, b_q)
}

